# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-24 14:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_create',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2016, 10, 24, 14, 7, 22, 338122, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='date_update',
            field=models.DateField(auto_now=True, default=datetime.datetime(2016, 10, 24, 14, 8, 39, 633641, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
