# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-24 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20161024_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
