# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-28 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='enable',
            field=models.BooleanField(default=False),
        ),
    ]
